import type { KeywordRule } from "./types";

/**
 * 테마별 검색 사전. 지역 추천은 ID의 마지막 분류, 개별 큐레이션은 themeIds에 연결한다.
 * keywords는 입력 동의어, metadata는 새 DB 테마의 제목·태그·무드에서 분류를 찾는 단어다.
 * 한 음절을 무조건 포함 검색하지 않는다. 새 표현은 이 사전에 명시적으로 추가한다.
 */
export const THEME_KEYWORD_TOPICS = [
  {
    id: "sea",
    label: "바다·해변",
    weight: 12,
    themeIds: ["east-sea-sunrise"],
    keywords: [
      "바다",
      "해변",
      "해수욕장",
      "해안",
      "항구",
      "일출",
      "해돋이",
      "일몰",
      "노을",
      "오션뷰",
      "해변산책",
      "바닷가",
      "파도",
      "해안드라이브",
      "드라이브",
      "sea",
      "beach",
      "ocean",
      "coast",
      "sunrise",
      "sunset",
      "drive",
    ],
    metadata: ["바다", "해변", "해안", "항구", "일출", "해돋이", "sea", "beach"],
  },
  {
    id: "mountain",
    label: "산·트레킹",
    weight: 12,
    themeIds: ["mountain-trek"],
    keywords: [
      "산",
      "등산",
      "산행",
      "트레킹",
      "하이킹",
      "정상",
      "설악산",
      "설악",
      "오대산",
      "오대",
      "태백산",
      "치악산",
      "mountain",
      "trek",
      "trekking",
      "hike",
      "hiking",
    ],
    metadata: ["산악", "등산", "산행", "트레킹", "하이킹", "mountain", "trek"],
  },
  {
    id: "local",
    label: "시장·먹거리",
    weight: 12,
    themeIds: ["market-local"],
    keywords: [
      "시장",
      "전통시장",
      "수산시장",
      "먹거리",
      "맛집",
      "맛있는",
      "먹",
      "미식",
      "로컬",
      "골목",
      "음식",
      "해산물",
      "횟집",
      "회",
      "국수",
      "막국수",
      "한우",
      "food",
      "market",
      "local",
      "restaurant",
      "seafood",
    ],
    metadata: ["시장", "먹거리", "맛집", "미식", "골목", "market", "food"],
  },
  {
    id: "cafe",
    label: "카페·사진",
    weight: 12,
    themeIds: ["cafe-viewpoint"],
    keywords: [
      "카페",
      "커피",
      "디저트",
      "감성",
      "사진",
      "포토",
      "뷰",
      "전망",
      "전망대",
      "커피거리",
      "cafe",
      "café",
      "coffee",
      "photo",
      "view",
      "dessert",
    ],
    metadata: ["카페", "커피", "포토", "사진", "cafe", "coffee"],
  },
  {
    id: "culture",
    label: "전시·예술",
    weight: 12,
    themeIds: [],
    keywords: [
      "미술관",
      "미술",
      "전시",
      "박물관",
      "뮤지엄",
      "예술",
      "갤러리",
      "문화",
      "실내",
      "비오는날",
      "비오는",
      "museum",
      "art",
      "gallery",
      "indoor",
      "rainy",
    ],
    metadata: ["전시", "미술", "박물관", "뮤지엄", "예술", "문화", "museum", "art"],
  },
  {
    id: "heritage",
    label: "역사·사찰",
    weight: 12,
    themeIds: [],
    keywords: [
      "역사",
      "사찰",
      "절",
      "유적",
      "문화재",
      "한옥",
      "고궁",
      "고택",
      "성곽",
      "템플스테이",
      "history",
      "heritage",
      "temple",
    ],
    metadata: ["역사", "사찰", "유적", "문화재", "한옥", "heritage", "temple"],
  },
  {
    id: "forest",
    label: "숲·산책",
    weight: 12,
    themeIds: ["quiet-inland"],
    keywords: [
      "숲",
      "숲길",
      "자작나무숲",
      "산책",
      "산책로",
      "둘레길",
      "걷",
      "걷기",
      "걸",
      "정원",
      "수목원",
      "휴양림",
      "삼림욕",
      "피톤치드",
      "내륙",
      "forest",
      "garden",
      "walk",
      "walking",
      "inland",
    ],
    metadata: ["숲", "숲길", "정원", "산책", "수목원", "휴양림", "forest", "garden"],
  },
  {
    id: "nature",
    label: "물길·자연",
    weight: 12,
    themeIds: [],
    keywords: [
      "계곡",
      "폭포",
      "동굴",
      "호수",
      "강변",
      "지질",
      "주상절리",
      "물놀이",
      "풍경",
      "자연",
      "lake",
      "river",
      "waterfall",
      "cave",
      "nature",
    ],
    metadata: ["계곡", "폭포", "동굴", "호수", "물길", "지질", "자연", "nature"],
  },
  {
    id: "family",
    label: "가족·체험",
    weight: 9,
    themeIds: ["family-experience"],
    keywords: [
      "가족",
      "아이",
      "아이들",
      "어린이",
      "아기",
      "체험",
      "목장",
      "양떼",
      "양떼목장",
      "동물",
      "놀이터",
      "놀이공원",
      "레일바이크",
      "family",
      "kids",
      "child",
      "children",
      "experience",
    ],
    metadata: ["가족", "체험", "목장", "어린이", "놀이", "family"],
  },
  {
    id: "quiet",
    label: "조용한 휴식",
    weight: 5,
    themeIds: ["quiet-inland"],
    keywords: [
      "조용",
      "한적",
      "한산",
      "고요",
      "힐링",
      "휴식",
      "쉬",
      "차분",
      "느긋",
      "여유",
      "혼자",
      "온천",
      "quiet",
      "calm",
      "relax",
      "rest",
      "alone",
      "healing",
    ],
    metadata: ["조용", "한적", "힐링", "휴식", "숲", "정원", "온천", "quiet", "calm"],
  },
] as const;

/** 개별 테마에 표현을 더할 때 사용한다. 지역 테마 113개는 위 분류 사전을 공유한다. */
export const THEME_EXTRA_KEYWORDS: Readonly<Record<string, readonly string[]>> = {
  "east-sea-sunrise": ["동해안", "해안도로"],
  "mountain-trek": ["설악", "오대", "산맥"],
  "market-local": ["재래시장", "먹방"],
  "cafe-viewpoint": ["카페투어", "사진명소"],
  "family-experience": ["키즈", "아이동반"],
  "quiet-inland": ["삼림욕", "명상"],
};

/** 기존 단일 테마 규칙을 쓰는 호출부도 같은 사전을 참조한다. */
export const THEME_KEYWORD_RULES: KeywordRule[] = THEME_KEYWORD_TOPICS.flatMap((topic) =>
  topic.themeIds.map((themeId) => ({
    themeId,
    keywords: [...topic.keywords, ...(THEME_EXTRA_KEYWORDS[themeId] ?? [])],
  })),
);
